### PR TITLE
Added model and its fields re RareUser

### PR DESCRIPTION
**Pull request by dontcallmeplath**
Added model and its fields re RareUser - migrated successfully on local machine

**TEST**: Pull branch and check that model migrates appropriately :)

### CODE REVIEW

**Review by triciaswift — APPROVED** [review]
Looks great!

**Review by ZachDAmico — APPROVED** [review]
nice

**Review by PhiferTristan — APPROVED** [review]
Looks good

**Review by PhiferTristan — APPROVED** [review]

**Review by ZachDAmico — APPROVED** [review]
i approve this message

**Pull request merged**
