### PR TITLE
Added comment list method & post retrieve method

### PR DESCRIPTION
**Pull request by triciaswift**
Added an `list` method to Comment View & `retrieve` method to Post View

Supported routes
`/comments?post=n` Will return an array of all the comments for that post
`/posts/n` Will return an object for a single post

### List Method
1. Pull down the `ts-comment-list-method` branch and switch to it
2. If your debugger is running, restart it
3. Open Postman
4. Change method to GET and request `http://localhost:8000/comments?post=n`
5. Use the following token
```
Token 978afa7b76527cc21d76d7b5430ab77f73aa3bff
```
6. The response should be an array of comments with the following properties:
```
[
    {
        "id": 6,
        "is_owner": false,
        "author": {
            "id": 2,
            "user": {
                "id": 2,
                "full_name": "Tristan Phifer"
            }
        },
        "content": "WOAH",
        "created_on": "11-22-2023",
        "post": 1
    },
    ...
]
```
8. Be sure you receive a 200 status code

### Retrieve Method
1. Change method to GET using `http://localhost:8000/posts/n`
2. You should receive a single object with the following properties:
```
{
    "id": 1,
    "title": "Example Post 1",
    "rare_user": {
        "id": 1,
        "user": {
            "id": 1,
            "full_name": "Carrie Belk"
        }
    },
    "category": {
        "id": 1,
        "label": "Lifestyle"
    },
    "publication_date": "2023-11-20",
    "content": "This is the content of Example Post 1."
}
```
3. Verify you receive a 200 status code

### CODE REVIEW

**Review by PhiferTristan — APPROVED** [review]
Very nice!

**Review by ZachDAmico — APPROVED** [review]
nice!

**Review by PhiferTristan — APPROVED** [review]
Workin great!

**Review by dontcallmeplath — APPROVED** [review]
Works here - thanks. Partially closes [ticket #5](https://github.com/NSS-Day-Cohort-66/rare-client-golden-droids-1/issues/5) re: view post details as well

**Pull request merged**
