### PR TITLE
Added update & retrieve method to tag view

### PR DESCRIPTION
**Pull request by triciaswift**
Added an `update` & `retrieve` method to Tag View

Supported routes
`/tags/n` Will return an object of a single tag in the response body for both methods

### Update Method
1. Pull down the `ts-tag-update` branch and switch to it
2. If your debugger is running, restart it
3. Open Postman
4. Change method to PUT using `http://localhost:8000/tags/n`
5. If you are an admin you should get a 204 status code
```
Token 978afa7b76527cc21d76d7b5430ab77f73aa3bff
```
6. The response you get back should have the following properties:
```
{
    "id": 2,
    "label": "tech"
}
```
7. If you are not an admin you should get a 403 status code
```
Token fa2eba9be8282d595c997ee5cd49f2ed31f65bed
```

### Retrieve Method
1. Change method to GET using `http://localhost:8000/tags/n`
2. You should receive a single object with the following properties:
```
{
    "id": 2,
    "label": "tech"
}
```
3. Verify you receive a 200 status code

### CODE REVIEW

**Review by PhiferTristan — APPROVED** [review]
Works great!

**Review by ZachDAmico — APPROVED** [review]
works!

**Review by PhiferTristan — APPROVED** [review]
Retrieve method works, as well!

**Review by dontcallmeplath — APPROVED** [review]
All good here :)

**Pull request merged**
